---
# tasks file for dellos10
 - name: "Generating BGP configuration for dellos10"
   template:
      src: dellos10_bgp.j2
      dest: "{{ build_dir }}/bgp10_{{ hostname }}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os10
   register: generate_output
   check_mode: no

 - name: "Provisioning BGP configuration for dellos10"
   dellos10_config:
      src: dellos10_bgp.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10")
#   notify: save config os10
   register: output
